# Generated by Django 2.0.2 on 2018-04-09 18:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_busstop', models.CharField(max_length=100)),
                ('end_busstop', models.CharField(max_length=100)),
                ('stops', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=101000, size=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Busstop',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bus_visit', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=101000, size=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adj_list', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=101000, size=1000)),
            ],
        ),
    ]
