# Generated by Django 2.0.2 on 2018-04-09 18:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adj_List', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=101000, size=1000)),
                ('dist_List', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('color', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_metrostation', models.CharField(max_length=100)),
                ('end_metrostation', models.CharField(max_length=100)),
                ('stations', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=101000, size=100)),
                ('distance', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
            ],
        ),
    ]
